
const gibsonSemiBold = "gibsonsemibold";
const robotoRegular = "robotoRegular";
const robotoMedium = "robotoMedium";
const robotoBold = "robotoBold";
const interRegular = "interRegular";
const interMedium = "interMedium";
const interBold = "interBold";
const robotoItalic = "robotoItalic";
const gibsonBold = "gibsonbold";
const gibsonRegular = "gibsonRegular";
const gibsonRegularItalic = "gibsonRegularItalic";


const assetPath = "assets/images/";
const preLoader = "${assetPath}splash.png";
const logo = "${assetPath}logo.png";
const comment = "${assetPath}comment.png";
const filter = "${assetPath}filter_arrow.png";
const filterAbove = "${assetPath}filterAbove.png";
const time = "${assetPath}time.png";
const chevronLeft = "${assetPath}chevronRight.png";
const chevronDown = "${assetPath}chevronDown.png";
const greenCheck = "${assetPath}greenCheckbox.png";
const greyCheck = "${assetPath}greyCheckBox.png";
const home = "${assetPath}memory.png";
const collab = "${assetPath}collab.png";
const publish = "${assetPath}publish.png";
const gallery = "${assetPath}image.png";
const fab = "${assetPath}FAB.png";
const add = "${assetPath}add.png";
const addMedia = "${assetPath}addMedia.png";
const addMemory = "${assetPath}addMemory.png";
const search = "${assetPath}search.png";
const fbSmall = "${assetPath}small_fb.png";
const instaSmall = "${assetPath}small_insta.png";
const driveSmall = "${assetPath}small_drive.png";
const book = "${assetPath}Icon.png";
const correct = "${assetPath}correct.png";
// const stashtLogo = "${assetPath}stasht_logo.svg";
const stashtLogo = "${assetPath}app_icon.svg";
const googleImage = "${assetPath}google 1.svg";
const appleImage = "${assetPath}apple_icon.svg";
const backgroundGradient = "${assetPath}background_gradient.png";
const folderIcon = "${assetPath}folder.svg";
const userIcon = "${assetPath}user.png";
const noMemories = "${assetPath}no_memories_icon.svg";
const checkBox = "${assetPath}checkbox.svg";
const pastaImage = "${assetPath}default-pasta.jpeg";
const noMemoriesPlaceholder = "${assetPath}no_memories_placeholder.png";
const eclipseImage = "${assetPath}eclipse.png";
const user = "${assetPath}user_icon.svg";
const emailIcon = "${assetPath}email_icon.svg";
const passwordIcon = "${assetPath}password_icon.svg";
const messageIcon = "${assetPath}message_icon.png";
const tickIcon = "${assetPath}tick_icon.png";
const copyIcon = "${assetPath}copy_icon.png";
const deleteIcon = "${assetPath}delete_icon.png";
const addPhotos = "${assetPath}add_photos.svg";
const addPhotosIcon = "${assetPath}add_photo_icon.png";
const publishIcon = "${assetPath}publish_icon.png";
const profileIcon = "${assetPath}profile.png";
const fbLogo = "${assetPath}facebookLogo.png";
const instaLogo = "${assetPath}Instagram_logo.png";
const camera = "${assetPath}camera.png";
const driveLogo = "${assetPath}drive_logo.png";



